"""empty message

Revision ID: 007dba64d5c8
Revises: be387e816213
Create Date: 2025-02-02 12:07:38.097557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007dba64d5c8'
down_revision = 'be387e816213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_species_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_species_key', ['species'])

    # ### end Alembic commands ###
