"""empty message

Revision ID: be387e816213
Revises: ffc7bd640deb
Create Date: 2025-01-31 18:31:38.141834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be387e816213'
down_revision = 'ffc7bd640deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('favourite_list', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_favourite_list_key', type_='unique')
        batch_op.drop_constraint('user_favourite_list_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_list', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_favourite_list_fkey', 'favourite_list', ['favourite_list'], ['id'])
        batch_op.create_unique_constraint('user_favourite_list_key', ['favourite_list'])

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('favourite_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
